### ISSUE TITLE
[Feature Request]: Vibration change

### ISSUE THREAD

**Issue by Anonuser-01** [jithware/brethap#109]
I really like the vibration function as I don't use the audio often, but I wish you can customize it. Currently it's the same vibration for inhale and exhale so if I am not fully aware I lose track whether it's inhale or exhale. It would be great if I can extend the inhale and exhale vibration.

**Comment by jithware** [comment]
Can you please describe the inhale/exhale periods that you are likely to lose track? 

When this happens to me and the periods are equal (as with the default of 4 seconds inhale + 4 seconds exhale), I just continue as usual, while not looking at the screen, because one is still maintaining the same breathing pattern. It may seem awkward if the session ends on the inhale, but I just follow through and exhale. When the periods are different, it's less likely to lose track since there is a noticeable difference. In this case I would just "self correct". Just an FYI if you were not already aware, when you set the vibration on a preset on your phone, it also applies to your watch when set to the [Phone](https://github.com/jithware/brethap_wear#custom) preset.

With that being said, I can definitely add this if other folks give it a "thumb up". Note this will likely lead to a [minor upgrade](https://github.com/jithware/brethap/discussions/48) because it will be adding a new preference.

**Comment by Anonuser-01** [comment]
Maybe I wasn't clear enough. 

Instead of just having "Breath Vibrate" at the bottom, I would like the vibration to be controlled individually for inhale and exhale, similar to how the audio for inhale and exhale can be controlled individually. 

It would be great if there was an option called inhale vibration next to inhale audio and same for exhale. 

I hope that clears it up. Thanks!

**Comment by jithware** [comment]
Thank you for the additional info. You were indeed clear previously. This is why I indicated it would require an additional preference. Breath vibrate would become inhale vibrate and additional exhale vibrate would be added.

To better understand where the issue occurs. Can you please describe the inhale/exhale periods that you are likely to lose track? For example, hypothetically if you set inhale to 1 second and exhale to 10 seconds, do you lose track? Or is it when they are equal, for example you set inhale to 4 seconds and exhale to 4 seconds?

Additionally, for feature requests, I ask individuals to help contribute, even if they are not developers. Could you please create an existing wireframe of [Preferences](https://github.com/jithware/brethap/blob/master/fastlane/metadata/android/en-US/images/phoneScreenshots/4_preferences.png) precisely as it is now? You will likely need two or more wireframes because scrolling in necessary to see the exhale portion. Once this is completed, create a new wireframe based off the existing with your new "Inhale Vibrate" and "Exhale Vibrate" added. Here are details on how to add wireframes: https://github.com/jithware/brethap/discussions/77. Once the wireframes are completed, we can leave this feature request open and allow other users to "Thumbs Up" it to indicate they are also interested in this feature, to better understand the demand. 

It may not be obvious to non-developers, but coding takes effort to do. Put another way, effort equals time and time should equal income. If a feature request demand is low and the effort/time is high and the income is low (or zero), then it doesn't make sense to do.

Hope this helps explain.

**Comment by Anonuser-01** [comment]
I have just been using the default settings with the 4 second inhale and exhale. 

I noticed you already had the vibration settings so I figured it wouldn't be as much work since you can re-use the same code. I do agree writing code is time consuming. You've done a great job with this app and I appreciate how feature rich it is. I especially love the watch integration which I use often.

I will look into the wireframe. For the time being, I have figured out a workaround by using the exhale hold. I have set the exhale hold to a low number so I basically get 2 vibrations (one for hold and one for inhale back to back) which tells me it's time to inhale again.

Thanks again for the quick replies!
