### ISSUE TITLE
[Feature Request]: Cache phone duration on watch

### ISSUE THREAD

**Issue by Anonuser-01** [jithware/brethap#110]
Hello,

I like the idea of setting a duration on the phone and having it sync'ed to the watch. Currently if the watch loses connection to the phone (usually happens when I go back to the watch app later when my phone isn't next to me), the duration I have set on the phone is not available. 

It would be great if the phone isn't connected, the last sync'ed duration is available.

Thanks!

**Comment by jithware** [comment]
Currently, the watch app does not maintain state when the app is closed. To retain the duration on the watch when no longer connected to the phone app, put the watch app into the background, instead of closing it. For example on the pixel watch, press the crown instead of swiping the app right to close it. Then bring the watch app to the foreground by launching it again and the duration will be retained. You will notice the phone icon on the watch will become grey indicating it is no longer connected to the phone and sessions will not be saved to the phone.
