### ISSUE TITLE
request: color option that works with no-blue / monochrome

### ISSUE THREAD

**Issue by wolftune** [jithware/brethap#18]
I wear blue-blocking glasses in times before bed. I might use brethap then, but the blue-on-black is nearly invisible (dark mode) and I don't want to use the blue-on-white (light-mode) which is too bright. I'd appreciate the option of the circle being orange or something like that. Orange-on-black would be clear still even in dim light with dim screen and blue-blocking glasses.

P.S. By far the best blue-blocking glasses are found cheaply by searching for "dental safety glasses", took me some trial and error to discover that. And there's more-orange vs more-red versions of those, and both have value since the dark red are so intense, there's near-zero visible color distinctions and the orange ones allow some more color but still nearly all blue is blocked.

**Comment by jithware** [comment]
In release >= 1.2.1+23

Changed the circle to use the theme primary color instead of a blue constant. This changes the circle to be more congruent with dark mode. Also submitted #20 to eventually allow customizing the theme color.

![screenshot](https://github.com/jithware/brethap/raw/d1299f9508e05e5ae7ee61697a72b251cae1f9c0/screenshots/android/home-dark.png)
