### ISSUE TITLE
Black text on dark background

### ISSUE THREAD

**Issue by wolftune** [jithware/brethap#25]
#23 is fixed, but now that I can choose dark background color, the text in the UI isn't adapting to be light when the background is dark. Thus, unreadable text. Dark on dark.

**Comment by jithware** [comment]
Fixed in release >= 1.4.1+27

Fix dark text in dark mode. Allow changing circle color in dark mode as described in https://github.com/jithware/brethap/issues/18. Unfortunately [Get.changeTheme()](https://pub.dev/documentation/get/latest/get_navigation_src_extension_navigation/GetNavigation.html#instance-methods) doesn't support changing theme while in dark mode. Color change takes affect upon application restart.

![](https://github.com/jithware/brethap/raw/80121e7c299b52dd3126c05c73a1b22190b21f3f/screenshots/android/running-dark.png)

**Comment by sollochs** [comment]
text still stays dark with dark background for me, doesn't change to white like in the screenshot above, on samsung oreo so no dark mode
using version 1.5.2+32
