### ISSUE TITLE
New language

### ISSUE THREAD

**Issue by lamvankhoat1** [jithware/brethap#29]
**Is your feature request related to a problem? Please describe.**
I'm Vietnamese, I just downloaded the app, I discovered that the app only supports English, so the tts function can only speak English
**Describe the solution you'd like**
I wish the application could allow users to contribute translations, so that the application can reach more people around the world

**Comment by jithware** [comment]
Internationalization support was added in #28 

@lamvankhoat1 please translate the following files to Vietnamese and submit a pull request.

https://github.com/jithware/brethap/blob/master/fastlane/metadata/android/vi/full_description.txt
https://github.com/jithware/brethap/blob/master/fastlane/metadata/android/vi/short_description.txt
https://github.com/jithware/brethap/blob/master/lib/l10n/app_vi.arb

**Comment by lamvankhoat1** [comment]
Thank you, I have updated the translation. Hope you will update the language in the app soon

**Comment by jithware** [comment]
@lamvankhoat1 I don't see a pull request. Did you submit one? See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by jithware** [comment]
Had to remove the [files](https://github.com/jithware/brethap/issues/29#issuecomment-1016407168) because it is producing warnings ```"vi": 2 untranslated message(s).``` and also deploys incorrect translations to [Google Play](https://play.google.com/store/apps/details?id=com.jithware.brethap). Need someone available to make updates presently and maintain in the future for it to make sense to have the translations.

Please use the English versions as a template, add the Vietnamese translated files and submit a [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) when complete.

**Comment by lamvankhoat1** [comment]
I finished the translation, and save it I think it's a pull request, you can recreate the files for me to re-translate and pull the request as soon as possible.
