### ISSUE TITLE
Vibration patterns for timing, inhale, hold and exhale 

### ISSUE THREAD

**Issue by rorar** [jithware/brethap#56]
Hey I enjoy Brethap, thanks for creating this App :)

Background:
I'd be happy if you would add vibration patterns to the app.
There are situations like traveling in public transportation, at workspace, in loud areas,... Where sounds would disturb you or persons around you. At some workspaces phones are not allowed, so this would help to sneaky do some breathing exercises. 

### Timing:
Every x ms between the inhale, hold and exhale sequences your phone vibrates x ms long. Like a clock is ticking. 
Optional: A more frequent / increased vibration at the beginning and/or end of an exercise will help you to know when the sequence is about to start/end. 
Is good for: This mimics the visual circle. 

### Inhale/hold/exhale;
You can setup your own pattern like
Inhale:  1 short vibration + 1 long vibration at x ms
Hold: 3 short vibrations at x ms
Exhale: 1 long vibration  + 1 short vibration.

You should be able to mix your own vibration patterns :)

**Comment by jithware** [comment]
I do like this idea. However I would like to keep the Preferences UI as simple as possible. For your suggestion, several new sliders would need to be added, the logic to know when to vibrate, storage updated to support new sliders, and testing for all updates. There's some significant work on this one. If enough other folks "up vote" this with a thumbs up, I'll take a look at it. If you have programming experience, preferably in dart/flutter, you could give a stab at it as well!

**Comment by jithware** [comment]
@rorar in order to better understand how to implement this, we'll need to put together some wireframes. I created a template for the preferences screen you can start from. Download the [preferences.drawio.xml](https://github.com/jithware/brethap/blob/master/wireframes/preferences.drawio.xml) file to your computer. Go to [draw.io](https://draw.io). Go to File->Open From->Device and open preferences.drawio.xml. Press the "+ More Shapes..." button in the bottom left and select "Material Design" from the "Other" category.

Create a **before** wireframe, mocking the existing Preferences screen as accurately as possible. Export to your device when complete by selecting File->Export As->XML be sure to uncheck "Compressed". 

Create an **after** wireframe with all of the configurable vibrations suggested above. Export to your device when complete. Fork the repo and add both xml files to [wireframes/](https://github.com/jithware/brethap/tree/master/wireframes). Submit a pull request.

Please try to make the wireframes look as close to the existing screen as possible as they will likely be used from here on out.

**Comment by sandoxy** [comment]
Maybe it woul be enought, to set constant vibration amounts: inhale 1 vibration, hold 2 vibrations and exhale 3 vibrations. Or would it be complicated, too? I miss this feature very much) But the app is also great without it)
